#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='/Users/claymore/.homebrew/bin/vim'
export VISUAL='/Users/claymore/.homebrew/bin/vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG=en_US.UTF-8
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
if (( $+commands[lesspipe.sh] )); then
  export LESSOPEN='| /usr/bin/env lesspipe.sh %s 2>&-'
fi

#
# Paths
#

typeset -gU cdpath fpath mailpath path
typeset -gxU MANPATH
typeset -gxUT INFOPATH infopath

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that info searches for manuals.
infopath=(
  /usr/local/share/info
  /usr/share/info
  $infopath
)

# Set the list of directories that man searches for manuals.
manpath=(
  /usr/local/share/man
  /usr/share/man
  $manpath
)

for path_file in /etc/manpaths.d/*(.N); do
  manpath+=($(<$path_file))
done
unset path_file

# Set the list of directories that Zsh searches for programs.
path=(
  /Users/claymore/.homebrew/bin
  /Users/claymore/go/bin
  /Users/claymore/Library/Python/2.7/bin
  /usr/local/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

for path_file in /etc/paths.d/*(.N); do
  path+=($(<$path_file))
done
unset path_file

#
# Temporary Files
#

if [[ -d "$TMPDIR" ]]; then
  export TMPPREFIX="${TMPDIR%/}/zsh"
  if [[ ! -d "$TMPPREFIX" ]]; then
    mkdir -p "$TMPPREFIX"
  fi
fi

# Oracle

export NLS_LANG=RUSSIAN_RUSSIA.UTF8

# Go

export GOPATH=$HOME/go

# Docker

export MACHINE_STORAGE_PATH=/Volumes/Warehouse/docker

# Colors

export GREP_COLOR='1;33'

if [ -e ~/.secrets ]; then
    source ~/.secrets
fi

# chruby
source /Users/claymore/.homebrew/opt/chruby/share/chruby/chruby.sh
source /Users/claymore/.homebrew/opt/chruby/share/chruby/auto.sh
